DROP DATABASE MAYO_DB;
CREATE DATABASE MAYO_DB;
USE MAYO_DB;

CREATE TABLE USER (
	USER_IDX INT PRIMARY KEY AUTO_INCREMENT,
	USERNAME VARCHAR(100) NOT NULL,
	PROVIDER VARCHAR(100) NOT NULL,
	PROVIDER_ID VARCHAR(100) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	ROLE VARCHAR(10) NOT NULL,
	JOINED_AT DATETIME NOT NULL,
	USER_STATUS CHAR DEFAULT 0,
	-- 사용자가 직접 추가할정보
	PHONE VARCHAR(20),
	BIRTH DATE,
	SCHOOL VARCHAR(20)
);

CREATE TABLE WORK (
	WORK_IDX INT PRIMARY KEY AUTO_INCREMENT,
	USER_IDX INT NOT NULL,
	CAT_IDX INT NOT NULL,
	WORK_TITLE VARCHAR(100) NOT NULL,
	WORK_CONTENT LONGTEXT NOT NULL,
	WORK_CREATED_AT DATETIME NOT NULL,
	WORK_STATUS CHAR DEFAULT 0
);

CREATE TABLE WORK_IMAGE (
	WORK_IMG_IDX INT PRIMARY KEY AUTO_INCREMENT,
	WORK_IDX INT NOT NULL,
	ORIG_FILE_NAME VARCHAR(100) NOT NULL,
	FILE_PATH VARCHAR(100) NOT NULL,
	FILE_SIZE INT NOT NULL
);

CREATE TABLE CATEGORY (
	CAT_IDX INT PRIMARY KEY AUTO_INCREMENT,
	CAT_NAME VARCHAR(10) NOT NULL
);

CREATE TABLE COMMENTS (
	COMM_IDX INT PRIMARY KEY AUTO_INCREMENT,
	WORK_IDX INT NOT NULL,
	USER_IDX INT NOT NULL,
	COMM_TITLE VARCHAR(100) NOT NULL,
	COMM_CONTENT TEXT NOT NULL,
	COMM_CREATED_AT DATETIME NOT NULL
);

CREATE TABLE LIKES (
	LIKE_IDX INT PRIMARY KEY AUTO_INCREMENT,
	WORK_IDX INT NOT NULL,
	USER_IDX INT NOT NULL
);

CREATE TABLE WISH (
	WISH_IDX INT PRIMARY KEY AUTO_INCREMENT,
	WORK_IDX INT NOT NULL,
	USER_IDX INT NOT NULL
);


ALTER TABLE WORK ADD CONSTRAINT FOREIGN KEY (USER_IDX) REFERENCES USER (USER_IDX);
ALTER TABLE WORK ADD CONSTRAINT FOREIGN KEY (CAT_IDX) REFERENCES CATEGORY (CAT_IDX);
ALTER TABLE WORK_IMAGE ADD CONSTRAINT FOREIGN KEY (WORK_IDX) REFERENCES WORK (WORK_IDX) ON DELETE CASCADE;
ALTER TABLE COMMENTS ADD CONSTRAINT FOREIGN KEY (WORK_IDX) REFERENCES WORK (WORK_IDX) ON DELETE CASCADE;
ALTER TABLE LIKES ADD CONSTRAINT FOREIGN KEY (WORK_IDX) REFERENCES WORK (WORK_IDX) ON DELETE CASCADE;
ALTER TABLE WISH ADD CONSTRAINT FOREIGN KEY (WORK_IDX) REFERENCES WORK (WORK_IDX) ON DELETE CASCADE;
ALTER TABLE WISH ADD CONSTRAINT FOREIGN KEY (USER_IDX) REFERENCES USER (USER_IDX) ON DELETE CASCADE;


insert into CATEGORY values (1, '서양화');
commit;

